Build a popup window
fahdrahali/fahdrahali.github.io pull request #16
Opened 2022-03-03 09:49 UTC by fahdrahali

**Create a popup window with details for desktop and mobile portfolio using:**
- Create project object.
- Use javascript to put data in HTML.
- Use JavaScript events.
- Use JavaScript to manipulate DOM elements.

2022-03-03 10:10 UTC, ReshyResh requested changes
# Hi @fahdrahali , 

### Good job so far!
  - ✔ Modal works as expected.
  - ✔ Styling matches the template.
  - ✔ No linter errors.


#### It seems like you forgot a big part of the requirement, but you're almost there with the milestone!


## Required Changes ♻️

- [ ] You currently still have hard-coded values for the project section, please follow the requirements and remove the hard coded sections, turning them dynamic and populating them with the informations from the objects that you will create.

_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

#### [OPTIONAL]

- [ ] In the range `600px-992px` your portfolio currently lacks styling. The reason behind it is your media queries settings, I suggest you also take a look at that section, to improve the user experience.

Cheers and Happy coding! 👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 10:10 UTC, ReshyResh commented on index.js
> +};
- [ ] Currently, you have only one object in the dynamic project. As per requirement, you should have an array of objects, one for each project, with their informations, and generate the works section dynamically getting the informations from each object. This means deleting the current hard-coded projects in `index.html` and writing a script that takes the information from the objects and generating each card individually. Please make sure to address these changes 👍

2022-03-03 10:10 UTC, ReshyResh commented on index.html
> +    <li><a href="#"><img src="./assets/images/btn-seelive-popup.png" alt="button see live"></a></li>
- [ ] Please, let's not use hard-coded images as buttons, instead, try styling your own to match the template, it will improve the interface, as images don't allow many interactions.

2022-03-04 00:49 UTC, gemmen29 approved these changes
Hi @fahdrahali, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-04 01:00 UTC, merged